image: "python:3.8"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V  # Print out python version for debugging
  - python -m venv venv
  - pip install -r requirements.txt
  - source venv/bin/activate

stages:
    - Static Analysis
    - Unit testing

flake8:
  stage: Static Analysis
  script:
    - flake8 api/app/ --ignore E402
    - flake8 scrape/ --ignore E402

pytest:
  stage: Unit testing
  script:
    - pytest . -v