version: '3'
services:
        app:
                container_name: news-scrape
                restart: always
                build: .
                ports:
                        - '8000:80'
                links:
                        - mongo
        mongo:
                container_name: mongo
                image: mongo
                ports:
                        - '27017:27017'
